# Generated by Django 4.1 on 2025-02-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='usertype',
            field=models.CharField(max_length=50),
        ),
    ]
