# Generated by Django 4.1 on 2025-04-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sbook_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbook',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sbook',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
