# Generated by Django 4.1 on 2025-04-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sbook_date_alter_sbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_sbook',
            name='adate',
            field=models.CharField(max_length=200),
        ),
    ]
